---
object_type: document
places:
  states:
    - backlog
    - sprint planning
    - sprint backlog
    - in progress
    - in review
    - testing
    - done
    - blocked
transitions:
  regular:
    - name: Move To Sprinter
      from: backlog
      to: sprint planning
      requires:
        - description
        - priority
    - name: Plan Issue
      from: sprint planning
      to: sprint backlog
      requires:
        - story_points
        - sprint
    - name: Start Work
      from: sprint backlog
      to: in progress
      requires:
        - assignee
    - name: Submit For Review
      from: in progress
      to: in review
      requires:
        - pull_request_url
    - name: Approve Review
      from: in review
      to: testing
      requires:
        - review_approvals
        - test_coverage
    - name: Pass Testing
      from: testing
      to: done
      requires:
        - qa_approved
        - deployment_approved
    - name: Reject Review
      from: in review
      to: in progress
      requires:
        - review_comments
    - name: Fail Testing
      from: testing
      to: in progress
      requires:
        - test_failure_reason
