---
object_type: document
places:
  states:
    - draft
    - pending review
    - reviewed
    - approved
    - rejected
transitions:
  regular:
    - name: Submit
      from: draft
      to: pending review
      requires:
        - valid_word_count
        - valid_clarity
        - valid_completeness
    - name: Review
      from: pending review
      to: reviewed
      requires:
        - valid_review_metrics
        - is_high_priority_or_urgent
    - name: Approve
      from: reviewed
      to: approved
      requires:
        - valid_approver
        - approved_status
    - name: Reject
      from: reviewed
      to: rejected
      requires:
        - has_rejection_reasons
    - name: Revise
      from: rejected
      to: draft
      requires: []
