---
object_type: document
places:
  states:
    - name: Draft
    - name: Pending Review
    - name: Reviewed
    - name: Approved
    - name: Rejected
transitions:
  regular:
    - name: Submit
      from: Draft
      to: Pending Review
      requires:
        - valid_word_count
        - valid_clarity
        - valid_completeness
    - name: Review
      from: Pending Review
      to: Reviewed
      requires:
        - valid_review_metrics
        - is_high_priority
        - is_urgent
    - name: Approve
      from: Reviewed
      to: Approved
      requires:
        - valid_approver
        - approved_status
    - name: Reject
      from: Reviewed
      to: Rejected
      requires:
        - has_rejection_reasons
    - name: Revisor
      from: Rejected
      to: Draft
      requires: []
metadata:
  rules: []
