---
object_type: Issue
places:
  states:
    - draft
    - pending_review
    - reviewed
    - approved
    - rejected
  special_states: []
transitions:
  regular:
    - name: submit
      from: draft
      to: pending_review
      requires:
        - valid_word_count
        - valid_clarity
        - valid_completeness
    - name: review
      from: pending_review
      to: reviewed
      requires:
        - valid_review_metrics
        - is_high_priority_or_urgent
    - name: approve
      from: reviewed
      to: approved
      requires:
        - valid_approver
        - approved_status
    - name: reject
      from: reviewed
      to: rejected
      requires:
        - has_rejection_reasons
    - name: revise
      from: rejected
      to: draft
      requires: []
